# This workflow runs unit tests against the minimum supported version
# of python on both ubuntu and windows.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  variables:
    name: Variables
    uses: ./.github/workflows/VariableProducer.yml

  unit-test:
    needs: [variables]
    name: MSV Validation
    uses: ./.github/workflows/UnitTestRunner.yml
    with:
      python-versions: ${{ needs.variables.outputs.python-msv }}
