##
# Azure Pipeline CI build and PR build

# Copyright (c), Microsoft Corporation
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
resources:
  repositories:
    - repository: pytool_extensions
      type: github
      name: tianocore/edk2-pytool-extensions
      ref: refs/heads/master
      endpoint: tianocore

# trigger on master for CI and all PRs for master
trigger: 
- master

pr: 
- master

jobs:
- template: azure-pipelines/templates/build-test-job.yml@pytool_extensions
  parameters:
    vm_image: 'windows-2022'
    root_package_folder: "edk2toollib"
    name: 'windows'
    codecov_enabled: true
    python_versions:
      # Job Titles cannot have periods, so we iterate
      # With a map using entry.key and entry.value
      '3_9': 3.9
      '3_10': 3.10
      '3_11': 3.11
